package tqs.lab5;

import com.microsoft.playwright.Page;
import com.microsoft.playwright.junit.UsePlaywright;
import com.microsoft.playwright.options.AriaRole;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Lab 5.6 - BlazeDemo Playwright Test
 * 
 * This test could be generated using Playwright codegen:
 * mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="codegen blazedemo.com"
 * 
 * 5.6c Analysis - Preferred locators used by Playwright codegen:
 * - Role-based locators (getByRole) - most robust
 * - Label-based locators (getByLabel)
 * - Text-based locators (getByText)
 * - Placeholder-based locators (getByPlaceholder)
 * 
 * Some locators may be fragile if:
 * - They rely on exact text that may change (translations, typos)
 * - They use positional selectors (nth-child, etc.)
 * - They use dynamic IDs or classes generated by frameworks
 */
@UsePlaywright
class BlazeDemoPlaywrightTest {

    @Test
    @DisplayName("5.6 - Complete flight booking flow")
    void testBookFlight(Page page) {
        // Navigate to homepage
        page.navigate("https://blazedemo.com/");
        assertThat(page.title()).isEqualTo("BlazeDemo");

        // Select departure and destination
        page.selectOption("select[name='fromPort']", "Boston");
        page.selectOption("select[name='toPort']", "Berlin");

        // Click Find Flights
        page.click("input[type='submit']");

        // Assert we're on the flights page
        assertThat(page.url()).contains("reserve");
        assertThat(page.title()).isEqualTo("BlazeDemo - reserve");

        // Choose first flight
        page.click("table tbody tr:nth-child(1) input[type='submit']");

        // Assert we're on purchase page
        assertThat(page.title()).isEqualTo("BlazeDemo Purchase");

        // Fill in passenger details
        page.fill("#inputName", "João Barreira");
        page.fill("#address", "123 Main Street");
        page.fill("#city", "Aveiro");
        page.fill("#state", "Aveiro");
        page.fill("#zipCode", "3800-000");
        page.selectOption("#cardType", "visa");
        page.fill("#creditCardNumber", "1234567890123456");
        page.fill("#creditCardMonth", "12");
        page.fill("#creditCardYear", "2025");
        page.fill("#nameOnCard", "João Barreira");

        // Purchase
        page.click("input[type='submit']");

        // Assert confirmation
        assertThat(page.title()).isEqualTo("BlazeDemo Confirmation");
        assertThat(page.locator("h1").textContent()).contains("Thank you for your purchase");
    }

    @Test
    @DisplayName("5.6 - Using role-based locators (more robust)")
    void testWithRoleBasedLocators(Page page) {
        page.navigate("https://blazedemo.com/");

        // Using getByRole for buttons - more semantic and robust
        page.getByRole(AriaRole.COMBOBOX).first().selectOption("Paris");
        page.getByRole(AriaRole.COMBOBOX).last().selectOption("Rome");

        // Click submit button by role
        page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Find Flights")).click();

        // Verify navigation
        assertThat(page.url()).contains("reserve");
    }

    @Test
    @DisplayName("5.6d - Refactored with improved locators")
    void testRefactoredWithBetterLocators(Page page) {
        page.navigate("https://blazedemo.com/");

        // Use semantic selectors
        page.locator("select[name='fromPort']").selectOption("Boston");
        page.locator("select[name='toPort']").selectOption("Cairo");

        // Use form submission
        page.locator("form").first().locator("input[type='submit']").click();

        // Wait for navigation and verify
        page.waitForURL("**/reserve.php**");
        assertThat(page.title()).contains("reserve");

        // Use table row locator
        page.locator("table.table tbody tr").first().locator("input").click();

        // Fill form using labels where possible
        page.locator("#inputName").fill("Test User");
        page.locator("#address").fill("Test Address");
        page.locator("#city").fill("Test City");
        page.locator("#state").fill("Test State");
        page.locator("#zipCode").fill("12345");
        
        // Submit purchase
        page.locator("input[value='Purchase Flight']").click();

        // Final assertion
        assertThat(page.title()).isEqualTo("BlazeDemo Confirmation");
    }
}
